name: Android CI

on:
  push:
    branches: [ "master" ]
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
  pull_request:
    branches: [ "master" ]
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    - name: set up JDK 11
=======
    - name: set up JDK 17
>>>>>>> Stashed changes
=======
    - name: set up JDK 17
>>>>>>> Stashed changes
=======
    - name: set up JDK 17
>>>>>>> Stashed changes
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create fake gradle.properties
      run: |
        touch gradle.properties
        echo KS=test >> gradle.properties
        echo KSPWD=test >> gradle.properties
        echo KALIAS=test >> gradle.properties
        echo KPWD=test >> gradle.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
